### ISSUE TITLE
Allow plugins to pass a priority (Error, Warning, ?)

### ISSUE THREAD

**Issue by aarongodin** [wookets/repoir#3]
Need to figure out how this would be defined, but I'd like a plugin to be able to give a level of "warning" to validations.

**Comment by coryroloff** [comment]
Currently, plugins return an array of objects with a message property. I'm thinking for this one we allow these objects to optionally contain a priority with "error" or "warn."

```js
[ { message: 'there was a problem', priority: 'error' } ]
```

The only thing I'm unhappy about is that we don't have any common pattern for plugin configuration. At the moment each plugin will have to decide if the user is able to choose the priority level.
